# Generated by Django 5.1.6 on 2025-03-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("agency_name", models.CharField(max_length=200)),
                ("gst_no", models.CharField(max_length=200)),
                ("address", models.TextField()),
            ],
        ),
    ]
