# Generated by Django 5.1.6 on 2025-05-06 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name="customuser",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inv_mng.organization"
            ),
        ),
    ]
