# Generated by Django 5.1.6 on 2025-03-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "inv_mng",
            "0002_item_rename_name_vendor_vendor_name_alter_vendor_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="vendor_name",
            new_name="vendor",
        ),
    ]
