# Generated by Django 5.1.6 on 2025-05-06 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0002_organization_alter_customuser_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inv_mng.organization",
            ),
        ),
    ]
