# Generated by Django 5.1.6 on 2025-03-10 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0003_rename_vendor_name_stock_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="InwardOutwardConv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inward_item_quantity", models.IntegerField()),
                ("outward_item_quantity", models.IntegerField()),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inv_mng.item"
                    ),
                ),
            ],
        ),
    ]
