# Generated by Django 5.1.6 on 2025-03-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0004_inwardoutwardconv"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="total_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
