# Generated by Django 5.1.6 on 2025-03-11 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0005_stock_total_quantity"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("department_id", models.AutoField(primary_key=True, serialize=False)),
                ("department_name", models.CharField(max_length=200)),
                ("poc_name", models.CharField(max_length=200)),
                (
                    "poc_contact",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="gst",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stock",
            name="department",
            field=models.CharField(default="NULL", max_length=200),
        ),
    ]
