# Generated by Django 5.1.6 on 2025-05-07 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0007_outwardstock_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastagestock",
            name="org",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inv_mng.organization",
            ),
        ),
    ]
