# Generated by Django 5.1.6 on 2025-03-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0007_remove_stock_department_inwardstock_outwardstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwardstock",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="inwardstock",
            name="total_price",
            field=models.IntegerField(default=0),
        ),
    ]
