# Generated by Django 5.1.6 on 2025-03-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0008_inwardstock_price_inwardstock_total_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwardstock",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
