# Generated by Django 5.1.6 on 2025-03-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0009_inwardstock_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwardstock",
            name="mrp",
            field=models.IntegerField(default=0),
        ),
    ]
