# Generated by Django 5.1.6 on 2025-03-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0010_inwardstock_mrp"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwardstock",
            name="gst_amount",
            field=models.IntegerField(default=0),
        ),
    ]
