# Generated by Django 5.1.6 on 2025-03-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0011_inwardstock_gst_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwardstock",
            name="bill_id",
            field=models.CharField(default="", max_length=200),
        ),
    ]
