# Generated by Django 5.1.6 on 2025-03-19 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0012_inwardstock_bill_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inwardstock",
            name="bill_id",
        ),
        migrations.CreateModel(
            name="InwardBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_id", models.CharField(max_length=50, unique=True)),
                ("bill_image", models.ImageField(upload_to="bills/")),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inv_mng.vendor"
                    ),
                ),
            ],
        ),
    ]
