# Generated by Django 5.1.6 on 2025-03-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0013_remove_inwardstock_bill_id_inwardbill"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwardstock",
            name="bill_id",
            field=models.CharField(default="", max_length=50),
        ),
    ]
