# Generated by Django 5.1.6 on 2025-03-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0014_inwardstock_bill_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwardstock",
            name="bill_image_path",
            field=models.CharField(default="", max_length=200),
        ),
    ]
