# Generated by Django 5.1.6 on 2025-03-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0015_inwardstock_bill_image_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwardstock",
            name="price_with_gst",
            field=models.BooleanField(default=False),
        ),
    ]
