# Generated by Django 5.1.6 on 2025-03-24 15:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0016_inwardstock_price_with_gst"),
    ]

    operations = [
        migrations.CreateModel(
            name="WastageStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "item_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="inv_mng.item"
                    ),
                ),
            ],
        ),
    ]
