# Generated by Django 5.1.6 on 2025-03-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0017_wastagestock"),
    ]

    operations = [
        migrations.AddField(
            model_name="wastagestock",
            name="wastage_amount",
            field=models.IntegerField(default=0),
        ),
    ]
