# Generated by Django 5.1.6 on 2025-03-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0018_wastagestock_wastage_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="outwardstock",
            name="outward_spent_amount",
            field=models.IntegerField(default=0),
        ),
    ]
