# Generated by Django 5.1.6 on 2025-03-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0019_outwardstock_outward_spent_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwardbill",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
