# Generated by Django 5.1.6 on 2025-03-27 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0021_inwardbill_price_with_gst"),
    ]

    operations = [
        migrations.AddField(
            model_name="inwardbill",
            name="bill_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
