# Generated by Django 5.1.6 on 2025-03-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inv_mng", "0022_inwardbill_bill_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inwardstock",
            name="gst_amount",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="inwardstock",
            name="price",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="inwardstock",
            name="total_price",
            field=models.FloatField(default=0.0),
        ),
    ]
