# Generated by Django 5.1.6 on 2025-04-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inv_mng",
            "0023_alter_inwardstock_gst_amount_alter_inwardstock_price_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="minimum_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
