services:
  - type: web
    name: inventory-management
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn inventory_mngmt.wsgi:application
    postdeployCommand: python manage.py migrate
    
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: inventory_mngmt.settings
      - key: SECRET_KEY
        generateValue: true
